version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network
    depends_on:
      - mysql
      - node

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=algoai
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  python:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./python:/app
    networks:
      - app-network

  node:
    image: node:16-slim
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
    networks:
      - app-network

  gcc:
    image: gcc:latest
    working_dir: /app
    volumes:
      - ./gcc:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 